apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-tcc-despesas
  namespace: despesas-prod
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: despesas-api.luisfelipe.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tcc-despesas-api-service
            port:
              number: 80
