# Role no namespace rotardv-qa para o Runner ter permissão de deploy no QA
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-runner-deployer-rotardv-qa
  namespace: rotardv-qa
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "replicasets", "pods", "services", "secrets", "configmaps", "persistentvolumeclaims", "ingresses", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# RoleBinding amarrando o SA (do tools) à Role (no rotardv-qa)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner-deployer-binding-rotardv-qa
  namespace: rotardv-qa
subjects:
  - kind: ServiceAccount
    name: gitlab-runner-rotardv-sa
    namespace: tools
roleRef:
  kind: Role
  name: gitlab-runner-deployer-rotardv-qa
  apiGroup: rbac.authorization.k8s.io
