---
# VOLUME PARA O MONGODB (QA)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-rotardv-qa-pvc
  namespace: rotardv-qa
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi

---
# BANCO DE DADOS (MONGODB - QA)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: rotardv-qa
spec:
  serviceName: "mongodb-rotardv"
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: docker.io/library/mongo:8
        envFrom:
        - secretRef:
            name: rotardv-qa-secrets
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: db-data
          mountPath: /data/db
        livenessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - db.adminCommand('ping')
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: mongodb-rotardv-qa-pvc

---
# SERVIÇO DO BANCO (O DNS INTERNO - QA)
apiVersion: v1
kind: Service
metadata:
  name: mongodb-rotardv
  namespace: rotardv-qa
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017

---
# API (QA)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotardv-api
  namespace: rotardv-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotardv-api
  template:
    metadata:
      labels:
        app: rotardv-api
    spec:
      containers:
      - name: rotardv-api
        image: docker.io/luisfelipe/rotardv-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5040
        envFrom:
        - secretRef:
            name: rotardv-qa-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 5040
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 5040
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1

---
# SERVIÇO DA API (QA)
apiVersion: v1
kind: Service
metadata:
  name: rotardv-api-service
  namespace: rotardv-qa
spec:
  selector:
    app: rotardv-api
  ports:
    - port: 80
      targetPort: 5040
