apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rotardv
  namespace: rotardv-qa
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: rotardv.api-qa.luisfelipe.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rotardv-api-service
            port:
              number: 80
